preset: recommended

risky: false

linting: true

enabled:
  - logical_not_operators_with_successor_space

disabled:
  - blankline_after_open_tag
  - namespace_no_leading_whitespace

finder:
  name:
    - "*.php"